version: "3"
services:
  eureka-service:
    image: micro-service/eureka-service
    ports:
      - 8000:8000
    hostname: eureka-service
  cat-service:
    image: micro-service/cat-service
    ports:
      - 8081:8081
    hostname: cat-service
    links:
      - eureka-service
    depends_on:
      - eureka-service
  dog-service:
    image: micro-service/dog-service
    ports:
      - 8082:8082
    hostname: dog-service
    links:
      - eureka-service
      - cat-service
    depends_on:
      - eureka-service