spring:
  application:
    name: EUREKA-SERVER
server:
  port: 8763
eureka:
  instance:
    hostname: eureka3        #Eureka实例的主机名
    prefer-ip-address: false
    instance-id: eureka3
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
      register-with-eureka: true
      fetch-registry: true
