spring:
  application:
    name: EUREKA-SERVER
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2        #Eureka实例的主机名
    prefer-ip-address: false
    instance-id: eureka2
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
      register-with-eureka: true
      fetch-registry: true
