spring:
  application:
    name: EUREKA-HA
server:
  port: 8761
eureka:
  instance:
    hostname: peer3        #Eureka实例的主机名
    prefer-ip-address: false
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8763/eureka/  #Eureka节点相互注册的
      register-with-eureka: true
      fetch-registry: true