spring:
  application:
    name: EUREKA-HA
server:
  port: 8763
eureka:
  instance:
    hostname: peer3        #Eureka实例的主机名
    prefer-ip-address: false
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
     # defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/  #Eureka节点相互注册的
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
      register-with-eureka: true
      fetch-registry: true
